FROM python:3.11-alpine

COPY pyproject.toml /pyproject.toml
COPY requirements/prod.txt /requirements.txt
COPY src/ /src/
COPY tests/ /tests/

COPY ../rss /rss/

# Install curl to perform health checks
RUN apk add --no-cache curl

RUN pip install -r /requirements.txt && pip install /rss/ && pip install .

WORKDIR /src
