version: "3"

services:

  cap-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: rss-api:latest
    container_name: cap-generator
    environment:
      - CONFIG=dev
      - API_URL=http://rss-api
      - API_USER=triton
      - API_PASSWORD=dog
      - CLIENT_IP=alerts-server
      - CLIENT_PORT=12250
    entrypoint: [
      "python",
      "rss/main.py"
    ]
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./feeds:/feeds

  alerts-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rss-api:latest
    container_name: cap-server
    environment:
      - CONFIG=dev
      - CLIENT_IP=alerts-server
      - CLIENT_PORT=12250
    entrypoint: [
      "python",
      "rss/test/server.py"
    ]
    volumes:
      - ./src:/src
      - ./tests:/tests
