version: "3"

services:

  cap-generator:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: rss-api:latest
    container_name: cap-generator
    env_file:
      - generator.env
    environment:
      - CONFIG=prod
    entrypoint: [
      "python",
      "rss/main.py"
    ]
    volumes:
      - ./feeds:/feeds